version: "3"

services:
  web:
    image: pmarino84/auth:$VERSION
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - $HOST_PORT:$PORT
      - 9229:9229 # debug port
    command: npm run serve