version: "3"

services:
  app:
    image: pmarino84/auth-dev:$VERSION
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .envdev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - $HOST_PORT:$PORT
      - $DEBUG_HOST_PORT:$DEBUG_PORT # debug port
    command: npm run serve