version: "3"

services:
  app:
    image: pmarino84/auth:$VERSION
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - SECRET_KEY=pasticcino
    volumes:
      - /usr/src/app/node_modules
    ports:
      - $HOST_PORT:$PORT
      - $DEBUG_HOST_PORT:$DEBUG_PORT # debug port